import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#393939",
        "on-error": "#690005",
        "primary-fixed-dim": "#aec6ff",
        surface: "#131314",
        "surface-container": "#1f2020",
        "primary-container": "#0070f3",
        "secondary-fixed-dim": "#c6c6cc",
        "on-surface": "#e4e2e2",
        "on-primary-fixed-variant": "#004397",
        background: "#131314",
        "tertiary-fixed-dim": "#48ddbc",
        "surface-container-highest": "#343535",
        "primary-fixed": "#d8e2ff",
        "inverse-surface": "#e4e2e2",
        "on-secondary-fixed-variant": "#45474b",
        "inverse-on-surface": "#303031",
        "tertiary-container": "#00866f",
        "outline-variant": "#414754",
        primary: "#aec6ff",
        "surface-dim": "#131314",
        "on-secondary-container": "#b7b8be",
        "on-tertiary": "#00382d",
        "on-tertiary-fixed-variant": "#005142",
        "secondary-container": "#47494e",
        outline: "#8b90a0",
        tertiary: "#48ddbc",
        "surface-tint": "#aec6ff",
        "on-primary-fixed": "#001a43",
        "surface-container-high": "#292a2a",
        "surface-container-lowest": "#0d0e0e",
        secondary: "#c6c6cc",
        "on-tertiary-fixed": "#002019",
        "secondary-fixed": "#e2e2e8",
        "surface-variant": "#343535",
        "on-primary": "#002e6b",
        "on-secondary-fixed": "#1a1c20",
        "tertiary-fixed": "#6bfad8",
        "on-primary-container": "#ffffff",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#0059c5",
        "on-tertiary-container": "#ffffff",
        "on-surface-variant": "#c1c6d7",
        error: "#ffb4ab",
        "on-secondary": "#2f3035",
        "error-container": "#93000a",
        "on-background": "#e4e2e2",
        "surface-container-low": "#1b1c1b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "sidebar-width": "280px",
        unit: "4px",
        "margin-desktop": "64px",
        gutter: "24px",
        "max-width-content": "1200px",
      },
      fontFamily: {
        "display-lg-mobile": ["Geist"],
        "code-sm": ["JetBrains Mono"],
        "display-lg": ["Geist"],
        "body-base": ["Inter"],
        "headline-md": ["Geist"],
        "label-caps": ["JetBrains Mono"],
      },
      fontSize: {
        "display-lg-mobile": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "code-sm": [
          "13px",
          { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" },
        ],
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "body-base": [
          "16px",
          { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "label-caps": [
          "11px",
          { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" },
        ],
      },
      maxWidth: {
        content: "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
