import { z } from 'zod';

export const updateSettingsSchema = z.object({
  displayName: z.string().min(1).max(100).optional(),
  tagline: z.string().max(200).optional(),
  avatar: z.string().optional().nullable(),
  favicon: z.string().optional().nullable(),
  siteTitle: z.string().max(200).optional(),
  metaDescription: z.string().max(500).optional(),
  bio: z.string().optional(),
  aboutContent: z.string().optional(),
  location: z.string().optional(),
  email: z.string().optional(),
  phone: z.string().optional(),
  resumeUrl: z.string().optional().nullable(),
  skills: z.array(z.object({
    name: z.string().min(1),
    level: z.number().min(0).max(100),
  })).optional(),
  socialLinks: z.array(z.object({
    name: z.string().default('').optional(),
    icon: z.string().default('link').optional(),
    url: z.string().min(1),
    show: z.boolean().optional(),
  })).optional(),
  experience: z.array(z.object({
    company: z.string().min(1),
    role: z.string().min(1),
    startDate: z.string().min(1),
    endDate: z.string().optional(),
    current: z.boolean().optional(),
    description: z.string().min(1),
    technologies: z.array(z.string()).optional(),
  })).optional(),
  education: z.array(z.object({
    institution: z.string().min(1),
    degree: z.string().min(1),
    field: z.string().min(1),
    startDate: z.string().min(1),
    endDate: z.string().optional(),
    current: z.boolean().optional(),
    description: z.string().optional(),
  })).optional(),
  certifications: z.array(z.object({
    name: z.string().min(1),
    issuer: z.string().min(1),
    date: z.string().min(1),
    url: z.string().optional(),
    description: z.string().optional(),
  })).optional(),
  forceDarkMode: z.boolean().optional(),
  contactEnabled: z.boolean().optional(),
  showSkills: z.boolean().optional(),
  showExperience: z.boolean().optional(),
  showEducation: z.boolean().optional(),
  showCertifications: z.boolean().optional(),
});
